//!/usr/bin/env groovy

pipeline{
    agent none
    stages {
        stage('Build'){
        	agent{
        	    	echo "Build finalizado"
        	    }
        	steps{
        	    sh "mvn package -Dmaven.test.skip=true"
        }
     }
   }
}
